services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_dev
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ventas_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  mongo:
    image: mongo:latest
    container_name: mongo_dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

  mongo-express:
    image: mongo-express
    container_name: mongo_admin_dev
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongo_dev:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - backend_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend_network

  api:
    container_name: api_service_dev
    build:
      context: ./MSG.SistemaVentas
      dockerfile: MSG.SistemaVentas.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    ports:
      - "31066:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend_network
    depends_on:
      - postgres
      - mongo